confirmed_guests = ['Alice', 'Charlie', 'Eve', 'Bob', 'Frank', 'Grace', 'David', 'Hannah', 'Liam', 'Mia']
print("Confirmed guests: ", confirmed_guests, "\n Stage 1")
waitlist = ['Ken', 'Jack','Ivy']
print("Waitlist: ", waitlist,"\n Stage 2")
waitlist.append("Noah")
waitlist.append("Oliver")
print("Waitlist: ", waitlist,"\n Stage 3")
confirmed_guests[0] = waitlist[0]
waitlist.remove(waitlist[0])
print("Confirmed guests: ", confirmed_guests, "\n Stage 4")
isCharlie = confirmed_guests.index("Charlie")
print(f'charlie is around and index {isCharlie} on the confirmed guest list', confirmed_guests, "\n Stage 5")
print("Waitlist: ", waitlist,"\n Stage 5")
confirmed_guests.remove("David")
confirmed_guests.remove("Eve")
print("Confirmed guests: ", confirmed_guests, "\n Stage 6")
print("Waitlist: ", waitlist,"\n Stage 6")
confirmed_guests.append(waitlist[0])
confirmed_guests.append(waitlist[1])
waitlist.pop(0)
waitlist.pop(0)
print("Confirmed guests: ", confirmed_guests, "\n Stage 7")
print("Waitlist: ", waitlist,"\n Stage 7")
waitlist.remove("Oliver")
print("Waitlist: ", waitlist,"\n Stage 8")
print(f'The last three guest on the list for the event planner are \n {confirmed_guests[7:]} \n', confirmed_guests, "\n Stage 9" )
confirmed_guests.append(waitlist[0])
waitlist.remove(waitlist[0])
print("Confirmed guests: ", confirmed_guests, "\n Stage 10")
print(f'The number of people that will be attending this event is {len(confirmed_guests)}\n',confirmed_guests, "\n Stage 11")
confirmed_guests.sort()
print("Confirmed guests: ", confirmed_guests, "\n Stage 12")
# confirmed_guests[confirmed_guests.index("Grace")] ,confirmed_guests[confirmed_guests.index("Noah")] = "Collins"
# print(confirmed_guests[0]) 
confirmed_guests.remove("Grace")
confirmed_guests.remove("Noah")
confirmed_guests.append("Collins")
confirmed_guests.sort()
print("Confirmed guests: ", confirmed_guests, "\n Stage 13")
print("guest_list_for_caterer: ", confirmed_guests, '\n Stage 14')
del waitlist